server:
  port: 8080

postgres:
  host: localhost:5432
  database: workout_bot_db
  username: postgres
  password: postgres

bot:
  name: Workout_notebook_bot
  token: ${BOT_TOKEN:}

admin:
  admin_id: ${TELEGRAM_ID:462874696}

spring:
  datasource:
    url: jdbc:postgresql://${postgres.host}/${postgres.database}
    username: ${postgres.username}
    password: ${postgres.password}
    driverClassName: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true

  liquibase:
    enabled: true
